name: Compress and Upload

on:
  push:
    branches:
      - main

jobs:
  compress_and_upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Obfuscate JS files
        run: npx javascript-obfuscator assets/js -o assets/js-obfuscated

      - name: Compress assets
        run: |
          mkdir compressed
          zip -r compressed/MikuAPI.zip ./

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: v0.0.1
          release_name: Release v0.0.1
          body: 开箱即用的API综合站点

          draft: false
          prerelease: false

      - name: Upload compressed assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./compressed/assets.zip
          asset_name: MikuAPI.zip
          asset_content_type: application/zip
